# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

resolver: lts-12.21

compiler-check: newer-minor

# Local packages, usually specified by relative directory name
packages:
- .

- location:
    /home/greg/hslibs/casadi-bindings/genpath/casadi-bindings-core

- location:
    /home/greg/hslibs/casadi-bindings/casadi-bindings-internal

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: [ spatial-math-0.4.0.0
#            , casadi-bindings-core-3.1.0.22
            ]
